[symphytum]
; redirect target (must include scheme + trailing slash)
server=http://127.0.0.1:3000/
; redirect target for asset requests
asset_server=http://127.0.0.1:3000/
; 0 = only error logs, 1 = error & info, 2 = error & info & debug
log_level=1
