[symphytum]
enable_patches=true
game_server=https://127.0.0.1:3000/
redirect_game_requests=true
asset_server=https://127.0.0.1:3000/
redirect_asset_requests=false
disable_encryption=true
disable_cert_pinning=true
use_custom_root_cert=false
; force the in-live autoplay judgement engine on even for normal runs
force_autoplay=true
; remap Auto judges to PerfectPlus so autoplay runs report like manual
fake_manual_result=true
; PEM string. Use literal \n or \r\n for multi-line certs
custom_root_cert=
; 0 = only error logs, 1 = error & info, 2 = error & info & debug
log_level=2
